In [78]:
import numpy as np

"""the difference between list and array"""
a = [[1,2,3,4],[5,6,7,8]]
b = np.array(a) # 列表转成数组   
c = b.tolist() #可将数组转成列表
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(a[0][:2])
print(b[0][:2])
a = a*2
b = b*2
print(a)
print(b)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'numpy.ndarray'>
[1, 2]
[1 2]
[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]
[[ 2  4  6  8]
 [10 12 14 16]]


In [38]:
"""生成数"""
c = np.arange(5,20,2) #类似range()的作用
print(c)
d = np.random.randn(12) #标准正态随机选取
print(d)
e = np.random.randint(0,10,(4,4)) #在0 和10之间随机取数生成4*4数组
print(e)

[ 5  7  9 11 13 15 17 19]
[ 1.35338648 -0.63630678  0.83970246  1.05402931  0.66648424 -0.24856663
  1.42816914  0.88993731  0.90374162 -0.50039106  0.53690667 -0.79577095]
[[8 2 4 9]
 [9 0 0 2]
 [9 1 3 4]
 [8 8 0 6]]


In [40]:
"""生成矩阵"""
f1 = np.ones((3,2)) #全一数组，shape为元组,默认浮点
f11 = np.ones((2,3,2))
f0 = np.zeros((3,2),dtype = np.int32) #全零数组，shape为元组，默认浮点
ff = np.full((3,2),5) #全value数组，shape为元组
fn = np.eye(3) #对角为1的n*n矩阵，默认浮点
f111 = np.ones_like(ff) #根据给定形状生成全1数组 类似的有 np.zeros_like(a),np.full_like(a,val)
print(f1)
print(f"\nshape is {f11.shape}\n{f11}")
print(f"\n{f0}")
print(f"\n{ff}")
print(f"\n{fn}")
print(f"\n{f111}")

[[1. 1.]
 [1. 1.]
 [1. 1.]]

shape is (2, 3, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

[[0 0]
 [0 0]
 [0 0]]

[[5 5]
 [5 5]
 [5 5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 1]
 [1 1]
 [1 1]]


In [41]:
"""数组填充和连结"""
a = np.linspace(1,10,4) #填充数组
b = np.linspace(1,10,4,endpoint = False)
c = np.concatenate((a,b))
print(a)
print(b)
print(c)

[ 1.  4.  7. 10.]
[1.   3.25 5.5  7.75]
[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [37]:
"""改变形状"""
d = np.random.randn(12)
d.reshape(3,4) #可以重组,但不改变原数组
print(d.reshape(3,4))
print(d)
d.resize(3,4) #可以重组,且改变原数组
print(d)
d = d.flatten() #降维打击，但不改变原数组
print(d)

[[ 1.24460124  0.95250294 -0.25056868 -1.3661428 ]
 [ 0.69874358  3.15180372  2.02317095  0.26329356]
 [-0.57390066  0.27493992 -1.35127451 -0.08433258]]
[ 1.24460124  0.95250294 -0.25056868 -1.3661428   0.69874358  3.15180372
  2.02317095  0.26329356 -0.57390066  0.27493992 -1.35127451 -0.08433258]
[[ 1.24460124  0.95250294 -0.25056868 -1.3661428 ]
 [ 0.69874358  3.15180372  2.02317095  0.26329356]
 [-0.57390066  0.27493992 -1.35127451 -0.08433258]]
[ 1.24460124  0.95250294 -0.25056868 -1.3661428   0.69874358  3.15180372
  2.02317095  0.26329356 -0.57390066  0.27493992 -1.35127451 -0.08433258]


In [55]:
a = np.ones((3,3),dtype = np.int) #np.int 叫整数类系统会根据数据自定义int32 或 int64
print(a)
b = a.astype(np.float) #复制a的数组并重新定义类型给b，a不变
print(b)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [64]:
"""索引和切片"""
a = np.arange(24).reshape((2,3,4))
print(a)
print(a[1,2,3]) #每个维度一个索引值，逗号分隔
print(a[-1,-2,-3])
print(a[:,1,-3]) #切片数组
print(a[:,1:3,:]) #一个维度一对中括号
print(a[:,:,::2]) #加上步长，跳跃式切片

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
23
17
[ 5 17]
[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [71]:
"""数组运算"""
a = np.arange(24).reshape(2,3,4)
print(a.mean())

11.5


In [72]:
"""例举一元函数"""
a = np.sqrt(a)
print(a)
b = np.modf(a) #分离整数和小数
print(a)

[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]
[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]


In [76]:
"""例举二元函数"""
a = np.arange(24).reshape(2,3,4)
b = np.sqrt(a)
print(a)
print(b)
c = np.maximum(a,b) #不仅取最大值，只要两个数据类型不同，就会进行取浮点
print(c)
d = a>b  #dtype = bool
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
[[[False False  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
