In [2]:
import numpy as np

"""the difference between list and array"""
a = [[1,2,3,4],[5,6,7,8]]
b = np.array(a) # 列表转成数组   
c = b.tolist() #可将数组转成列表
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(a[0][:2])
print(b[0][:2])
a = a*2
b = b*2
print(a)
print(b)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'numpy.ndarray'>
[1, 2]
[1 2]
[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]
[[ 2  4  6  8]
 [10 12 14 16]]


In [20]:
"""生成数和随机数"""
c = np.arange(5,20,2) #类似range()的作用
print(c)
d = np.random.randn(3,4,5) #标准正态随机选取
print(d)
d = np.random.uniform(0,10,(3,4))
d = np.random.normal(10,5,(3,4))
e = np.random.randint(0,10,(4,4)) #在0 和10之间随机取数生成4*4数组
print(e)
np.random.seed(10) #调用，生成伪随机数
k = np.random.randint(100,200,(3,4))
print(k)
np.random.seed(10) #再次调用，生成相同伪随机数
j = np.random.randint(100,200,(3,4))
print(j)
np.random.shuffle(j) #永久性随机改变j的最外层的一维数组顺序
print(j)
np.random.permutation(j) #临时性随机改变j的最外层的一维数组顺序
print(j)
b1 = np.random.randint(100,200,(8,))
b2 = np.random.choice(b1,(3,2),replace = False,p=b1/np.sum(b1)) #从一维数组中随机挑选，默认可以重复选,制定概率
print(b2)

[ 5  7  9 11 13 15 17 19]
[[[-1.58494101e+00  1.05535316e+00 -1.92657911e+00  6.98583878e-01
   -7.46201430e-01]
  [-1.56626664e-01 -1.93635938e-01  1.13912535e+00  3.62217963e-01
   -5.90912985e-01]
  [ 3.89363045e-01 -5.26996152e-01 -5.14307908e-01  8.97609175e-01
    9.89252087e-01]
  [ 2.59225131e-01 -2.41931902e-02  3.58496663e-01 -3.77546365e-01
    6.95631162e-01]]

 [[ 1.02484465e+00  1.70775544e+00 -1.96711722e+00 -8.70956667e-01
   -1.10682548e+00]
  [ 2.75123658e-01 -3.64456144e-01 -1.16515347e+00 -1.34306988e+00
    1.45339286e+00]
  [ 1.16944865e-03 -1.19203847e-02  7.15883143e-01 -1.18576855e+00
   -6.36327905e-01]
  [-6.10813844e-01 -1.31939140e+00 -5.61728416e-01  2.05384574e-01
   -9.53360676e-01]]

 [[ 3.21517951e-01 -1.52093867e+00 -2.16145292e+00  3.45313294e-01
    8.78969384e-01]
  [ 5.62763006e-01  2.88435337e-01 -1.00648150e+00  5.39784210e-02
   -1.82672326e+00]
  [-9.19148358e-02 -2.53183164e-01  1.38059377e+00 -6.83428827e-01
   -3.16851151e-01]
  [-1.0172704

In [11]:
"""统计值"""
a = np.arange(18).reshape(2,3,3)
print(a)
b = np.sum(a) #统计值默认全部计算
print(b)
c = np.mean(a,axis=1) #表示将第二维数据进行运算 0代表最外围
print(c)
c = np.median(a)
d = np.average(a,axis=0,weights=(1,2)) # 6=(1*0+2*9)/(1+2) 加权平均
print(d)
e = np.std(a)
f = np.var(a)
g = np.min(a) # max(a)
g = np.argmin(a) #argmax(a) 获取最大值最小值的扁平化后的下标位置
print(g)
k = np.unravel_index(np.argmin(a),a.shape) #重塑成多维下标 和argmin经常一起使用
print(k)
g = np.ptp(a) #最大值和最小值的差

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
153
[[ 3.  4.  5.]
 [12. 13. 14.]]
[[ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
0
(0, 0, 0)


In [14]:
"""梯度，放映变化率，常用于声音图像数据处理"""
#一维梯度
a = np.random.randint(0,20,(5))
print(a)
a1 = np.gradient(a) #x2梯度 = (x3-x1)/2   x1梯度 = (x2-x1)/1 
print(a1)
#二维梯度
b = np.random.randint(0,20,(3,4))
print(b)
b1 = np.gradient(b) #二维数组会生成最外层维度梯度值，和第二层维度梯度值，
print(b1)

[14  2 14 18  9]
[-12.    0.    8.   -2.5  -9. ]
[[18  9  9  7]
 [18  5  5 10]
 [13 18 10  8]]
[array([[ 0. , -4. , -4. ,  3. ],
       [-2.5,  4.5,  0.5,  0.5],
       [-5. , 13. ,  5. , -2. ]]), array([[ -9. ,  -4.5,  -1. ,  -2. ],
       [-13. ,  -6.5,   2.5,   5. ],
       [  5. ,  -1.5,  -5. ,  -2. ]])]


In [40]:
"""生成矩阵"""
f1 = np.ones((3,2)) #全一数组，shape为元组,默认浮点
f11 = np.ones((2,3,2))
f0 = np.zeros((3,2),dtype = np.int32) #全零数组，shape为元组，默认浮点
ff = np.full((3,2),5) #全value数组，shape为元组
fn = np.eye(3) #对角为1的n*n矩阵，默认浮点
f111 = np.ones_like(ff) #根据给定形状生成全1数组 类似的有 np.zeros_like(a),np.full_like(a,val)
print(f1)
print(f"\nshape is {f11.shape}\n{f11}")
print(f"\n{f0}")
print(f"\n{ff}")
print(f"\n{fn}")
print(f"\n{f111}")

[[1. 1.]
 [1. 1.]
 [1. 1.]]

shape is (2, 3, 2)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

[[0 0]
 [0 0]
 [0 0]]

[[5 5]
 [5 5]
 [5 5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 1]
 [1 1]
 [1 1]]


In [41]:
"""数组填充和连结"""
a = np.linspace(1,10,4) #填充数组
b = np.linspace(1,10,4,endpoint = False)
c = np.concatenate((a,b))
print(a)
print(b)
print(c)

[ 1.  4.  7. 10.]
[1.   3.25 5.5  7.75]
[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]


In [37]:
"""改变形状"""
d = np.random.randn(12)
d.reshape(3,4) #可以重组,但不改变原数组
print(d.reshape(3,4))
print(d)
d.resize(3,4) #可以重组,且改变原数组
print(d)
d = d.flatten() #降维打击，但不改变原数组
print(d)

[[ 1.24460124  0.95250294 -0.25056868 -1.3661428 ]
 [ 0.69874358  3.15180372  2.02317095  0.26329356]
 [-0.57390066  0.27493992 -1.35127451 -0.08433258]]
[ 1.24460124  0.95250294 -0.25056868 -1.3661428   0.69874358  3.15180372
  2.02317095  0.26329356 -0.57390066  0.27493992 -1.35127451 -0.08433258]
[[ 1.24460124  0.95250294 -0.25056868 -1.3661428 ]
 [ 0.69874358  3.15180372  2.02317095  0.26329356]
 [-0.57390066  0.27493992 -1.35127451 -0.08433258]]
[ 1.24460124  0.95250294 -0.25056868 -1.3661428   0.69874358  3.15180372
  2.02317095  0.26329356 -0.57390066  0.27493992 -1.35127451 -0.08433258]


In [55]:
a = np.ones((3,3),dtype = np.int) #np.int 叫整数类系统会根据数据自定义int32 或 int64
print(a)
b = a.astype(np.float) #复制a的数组并重新定义类型给b，a不变
print(b)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [64]:
"""索引和切片"""
a = np.arange(24).reshape((2,3,4))
print(a)
print(a[1,2,3]) #每个维度一个索引值，逗号分隔
print(a[-1,-2,-3])
print(a[:,1,-3]) #切片数组
print(a[:,1:3,:]) #一个维度一对中括号
print(a[:,:,::2]) #加上步长，跳跃式切片

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
23
17
[ 5 17]
[[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [71]:
"""数组运算"""
a = np.arange(24).reshape(2,3,4)
print(a.mean())

11.5


In [72]:
"""例举一元函数"""
a = np.sqrt(a)
print(a)
b = np.modf(a) #分离整数和小数
print(a)

[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]
[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]


In [76]:
"""例举二元函数"""
a = np.arange(24).reshape(2,3,4)
b = np.sqrt(a)
print(a)
print(b)
c = np.maximum(a,b) #不仅取最大值，只要两个数据类型不同，就会进行取浮点
print(c)
d = a>b  #dtype = bool
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0.         1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974 2.64575131]
  [2.82842712 3.         3.16227766 3.31662479]]

 [[3.46410162 3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069 4.35889894]
  [4.47213595 4.58257569 4.69041576 4.79583152]]]
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
[[[False False  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [16]:
"""数据存储"""
"""store data as csv"""
a = np.arange(100).reshape(5,20)
np.savetxt("a.csv",a,fmt="%d",delimiter = ",")  #%d 意为保存为整数， %.1f是一位小数

In [17]:
"""read csv"""
b = np.loadtxt("a.csv",delimiter = ",") #会读成浮点
print(b)
b = np.loadtxt("a.csv",dtype = np.int, delimiter = ",")
print(b)
"""注意 csv 只能存储一维和二维数组"""

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
  38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57.
  58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74. 75. 76. 77.
  78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97.
  98. 99.]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


'注意 csv 只能存储一维和二维数组'

In [18]:
"""多维数组存取"""
a = np.arange(100).reshape(2,10,5)
a.tofile("b.dat",sep=",",format = "%d") #data格式，默认format为二进制
c = np.fromfile("b.dat",dtype = np.int,sep=",") #维度信息会丢失
print(c)
c = np.fromfile("b.dat",dtype = np.int,sep=",").reshape(2,10,5) #需要重新定义维度
print(c)
"""一般这种形式数据不仅要储存起来，还要写个数据包含维度，数据类型等信息"""

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


'一般这种形式数据不仅要储存起来，还要写个数据包含维度，数据类型等信息'

In [19]:
"""多维数组存取，numpy自定义格式"""
a = np.arange(100).reshape(2,10,5)
np.save("a.npy",a) #np.save可以将数据以二进制存储，并在第一行记录数据信息，用于读取
b = np.load("a.npy")
print(b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]
